apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::561828308876:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RKAAKH7EFMWU
      username: system:node:{{EC2PrivateDNSName}}
      rolearn: arn:aws:iam::561828308876:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2019-11-03T11:21:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "898"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 067243fc-fe2c-11e9-bde0-0efd6c811d68
