apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::561828308876:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-9IO6PWDR2HLT
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2019-11-02T07:38:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "778"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c39e1e7a-fd43-11e9-ac54-029e51d9de5e
